title: PayItMonthly Integration Guide &laquo; PayItMonthly
baseurl: /integration
markdown: kramdown
redcarpet:
    extensions: [with_toc_data, tables, fenced_code_blocks]
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
gems:
    - jekyll-redirect-from
